CREATE TABLE `hrs_permission` (
  `permission_id` int(11) NOT NULL AUTO_INCREMENT,
  `permission_code` varchar(20) NOT NULL,
  `permission_name` varchar(40) NOT NULL,
  `path` varchar(255) DEFAULT NULL COMMENT '前端链接，如果 路径是 /unDevelop 则 跳转到 暂未开通页面',
  `url` varchar(255) DEFAULT NULL COMMENT 'vue链接',
  `permission` varchar(255) DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `parent_ids` varchar(255) DEFAULT NULL,
  `sort` int(11) DEFAULT NULL,
  `status` int(1) DEFAULT '0' COMMENT '0:启用 1:删除',
  `permission_type` varchar(20) NOT NULL,
  `creator_id` int(11) DEFAULT NULL,
  `create_time` datetime NOT NULL,
  `stop_date` datetime DEFAULT NULL,
  `app_code` varchar(20) NOT NULL,
  `disabled` varchar(20) DEFAULT NULL COMMENT '不可分配',
  `admin_default` varchar(20) DEFAULT NULL COMMENT '默认给管理员',
  `able_Orgid` varchar(20) DEFAULT NULL,
  `help_document_name` varchar(30) DEFAULT NULL COMMENT '帮助文档名称',
  `help_document_url` varchar(100) DEFAULT NULL COMMENT '帮助文档路径',
  `customized` bit(1) DEFAULT b'0' COMMENT '定制菜单',
  `url_crud` tinyint(4) DEFAULT NULL,
  `mapping_url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`permission_id`) USING BTREE,
  KEY `IDU_hrs_permission_SY_01` (`permission_id`,`path`,`url`,`parent_id`,`sort`,`permission`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1303 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC COMMENT='HRS 权限管理';




INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (1, '001', '组织机构管理', '', '', '', 'el-icon-office-building', -1, '-1', 1, 1, '0', 1, '2019-06-13 10:10:18', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (2, '001006', '用户管理', '/hrs_user', '/hrs_user', '', '', 1, '1', 6, 1, '1', 1, '2019-06-18 13:15:06', NULL, 'HRS', 'false', 'true', NULL, '用户管理-2020.12.29.pdf', 'http://doc.efreight.cn/public/help/help_document_210322104540_用户管理-2020.12.29.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (3, '001006001', '添加用户', '', '', 'sys_user_add', NULL, 2, '1,2', 1, 1, '2', 1, '2019-06-19 11:24:02', NULL, 'HRS', 'false', 'true', NULL, '', '', b'0', 1, '/user/saveUser');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (4, '002', '客商资料管理', '', NULL, NULL, 'el-icon-user', -1, '-1', 3, 1, '0', 1, '2019-06-21 16:09:36', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (5, '001004', '权限管理', '/hrs_permission', '/hrs_permission', '', 'el-icon-s-check', 1, '1', 4, 1, '1', 1, '2019-06-24 15:01:04', NULL, 'HRS', 'true', 'true', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (6, '001004001', '新增权限', '', NULL, 'sys_menu_add', NULL, 5, '1,5', 1, 1, '2', 1, '2019-06-24 15:03:12', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 1, '/permission/save');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (7, '001001', '签约公司', '/hrs_org', '/hrs_org', '', 'el-icon-s-management', 1, '1', 1, 1, '1', 1, '2019-06-24 15:23:54', NULL, 'HRS', 'true', 'false', NULL, 'MAWB.pdf', 'http://doc.efreight.cn/public/help/help_document_210330150752_MAWB.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (8, '001001001', '保存签约客户', '', '', 'sys_org_add', NULL, 7, '1,7', 1, 1, '2', 1, '2019-06-24 15:25:38', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 1, '/org');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (9, '001001002', '修改签约客户', '', '', 'sys_org_edit', NULL, 7, '1,7', 2, 1, '2', 1, '2019-06-24 15:50:53', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 3, '/org');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (10, '001001003', '删除签约客户', '', '', 'sys_org_del', NULL, 7, '1,7', 3, 1, '2', 1, '2019-06-24 15:51:37', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 2, '/org/{id}');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (11, '001004002', '修改权限', '', '', 'sys_menu_edit', NULL, 5, '1,5', 2, 1, '2', 1, '2019-06-24 15:53:39', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 3, '/permission');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (12, '001004003', '删除权限', '', '', 'sys_menu_del', NULL, 5, '1,5', 3, 1, '2', 1, '2019-06-24 15:54:01', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 2, '/permission/{id}');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (13, '001006002', '修改用户', '', '', 'sys_user_edit', NULL, 2, '1,2', 2, 1, '2', 1, '2019-06-24 15:59:21', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/user/edit');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (14, '001006003', '删除用户', '', '', 'sys_user_del', NULL, 2, '1,2', 3, 0, '2', 1, '2019-06-24 15:59:35', NULL, 'HRS', 'true', 'true', NULL, NULL, NULL, b'0', 2, '/user/{id}');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (15, '001004', '部门管理', '/hrs_dept', '/hrs_dept', '', '', 1, '1', 4, 0, '1', 1, '2019-06-24 16:01:05', NULL, 'HRS', 'true', 'true', NULL, '部门管理-2020.12.29 (2).pdf', 'http://doc.efreight.cn/public/help/help_document_210322104154_部门管理-2020.12.29 (2).pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (16, '001004001', '新建部门', '', '', 'sys_dept_add', NULL, 15, '1,15', 1, 1, '2', 1, '2019-06-24 16:02:05', NULL, 'HRS', 'false', 'true', NULL, '部门管理-2020.12.29 (2).pdf', 'http://doc.efreight.cn/public/help/help_document_210322163813_部门管理-2020.12.29 (2).pdf', b'0', 1, '/dept');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (17, '001004002', '修改部门', '', '', 'sys_dept_edit', NULL, 15, '1,15', 2, 1, '2', 1, '2019-06-24 16:02:19', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/dept');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (18, '001004003', '删除部门', '', '', 'sys_dept_del', NULL, 15, '1,15', 3, 1, '2', 1, '2019-06-24 16:02:46', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 2, '/dept/{id}');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (19, '001005', '角色管理', '/hrs_role', '/hrs_role', '', '', 1, '1', 5, 1, '1', 1, '2019-06-24 16:03:26', NULL, 'HRS', 'false', 'true', NULL, '角色管理-21.7.30.pdf', 'http://doc.efreight.cn/public/help/help_document_210730155552_角色管理-21.7.30.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (20, '001005001', '新建角色', '', '', 'sys_role_add', NULL, 19, '1,19', 1, 1, '2', 1, '2019-06-24 16:04:16', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 1, '/role/save');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (21, '001005002', '修改角色', '', '', 'sys_role_edit', NULL, 19, '1,19', 2, 1, '2', 1, '2019-06-24 16:04:28', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/role/edit');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (22, '001005003', '删除角色', '', '', 'sys_role_del', NULL, 19, '1,19', 3, 1, '2', 1, '2019-06-24 16:04:42', NULL, 'HRS', 'true', 'true', NULL, NULL, NULL, b'0', 2, '/role/{id}');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (23, '002001', '客商资料', '/prm_coop', '/prm_coop', NULL, 'el-icon-keshangziliao iconfont2', 4, '4', 1, 1, '1', 1, '2019-06-25 14:05:27', NULL, 'PRM', 'false', 'false', NULL, '客商资料-21.3.29.pdf', 'http://doc.efreight.cn/public/help/help_document_210330143747_客商资料-21.3.29.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (24, '001005004', '更新角色菜单', '', '', 'sys_role_perm', NULL, 19, '1,19', 4, 0, '2', 1, '2019-06-26 16:48:22', NULL, 'HRS', 'true', 'true', NULL, NULL, NULL, b'0', 3, '/role/menu');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (37, '002005', '参数管理', '/prm_category', '/prm_category', '', 'el-icon-s-data', 4, '4', 5, 1, '1', 1, '2019-06-28 14:37:29', NULL, 'PRM', 'true', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (39, '002006', '日志管理', '/prm_log', '/prm_log', '', 'el-icon-printer', 4, '4', 6, 1, '1', 1, '2019-07-01 10:43:51', NULL, 'PRM', 'true', 'true', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (41, '004002', '空运信息', '', '', '', 'el-icon-s-tools', 268, '268', 2, 0, '1', 3, '2019-07-16 10:26:35', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (42, '001007', '公告管理', '/hrs_notice', '/hrs_notice', '', 'el-icon-message', 1, '1', 7, 0, '1', 3, '2019-07-17 13:49:41', NULL, 'HRS', 'true', 'true', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (43, '001008', '版本管理', '/hrs_version', '/hrs_version', NULL, 'el-icon-notebook-2', 1, '1', 8, 1, '1', 3, '2019-07-22 09:55:55', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (46, '001009', '日志管理', '/hrs_log', '/hrs_log', '', '', 1, '1', 9, 0, '1', 4, '2019-08-13 16:23:38', NULL, 'HRS', 'true', 'true', NULL, '日志管理-2020.12.28.pdf', 'http://doc.efreight.cn/public/help/help_document_210322104913_日志管理-2020.12.28.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (50, '001006004', '导出用户', '', '', 'sys_user_export', '', 2, '2,1', 4, 1, '2', 58, '2019-08-23 15:59:17', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 6, '/user/exportExcel');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (51, '001006005', '离职', '', '', 'sys_user_leave', '', 2, '2,1', 5, 1, '2', 58, '2019-08-23 16:05:18', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/user/leave');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (52, '001006006', '复职', '', '', 'sys_user_resume', '', 2, '2,1', 6, 1, '2', 58, '2019-08-23 16:05:44', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/user/resume/');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (53, '001006011', '黑名单', '', '', 'sys_user_black', '', 2, '2,1', 11, 1, '2', 58, '2019-08-23 16:06:17', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/user/black');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (54, '001006008', '兼职新增', '', '', 'sys_user_parttime_save', '', 2, '2,1', 8, 1, '2', 58, '2019-08-23 16:07:15', NULL, 'HRS', 'true', 'true', NULL, NULL, NULL, b'0', NULL, '');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (55, '001006010', '重置密码', '', '', 'sys_user_resetpass', '', 2, '2,1', 10, 1, '2', 58, '2019-08-23 16:07:39', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/user/resetPassward/{userId}');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (56, '001004004', '移动部门', '', '', 'sys_dept_move', '', 15, '15,1', 4, 1, '2', 58, '2019-08-23 16:08:08', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/dept/moveById');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (57, '001004005', '排序部门', '', '', 'sys_dept_sort', '', 15, '15,1', 5, 1, '2', 58, '2019-08-23 16:09:31', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/dept/sortById');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (58, '001004006', '合并部门', '', '', 'sys_dept_merge', '', 15, '15,1', 6, 1, '2', 58, '2019-08-23 16:09:51', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 3, '/dept/mergeById');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (59, '002001001', '新建客商资料', '', '', 'sys_coop_add', '', 23, '23,4', 1, 1, '2', 58, '2019-08-23 16:10:32', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', 1, '/coop/saveCoop');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (60, '002001002', '修改客商资料', '', '', 'sys_coop_edit', '', 23, '23,4', 2, 1, '2', 58, '2019-08-23 16:10:52', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (61, '002001003', '导出客商资料', '', '', 'sys_coop_export', '', 23, '23,4', 3, 1, '2', 58, '2019-08-23 16:11:14', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', 6, '/coop/exportExcel');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (62, '002001007', '黑名单', '', '', 'sys_coop_black', '', 23, '23,4', 7, 1, '2', 58, '2019-08-23 16:11:33', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', 3, '/coop/modifyBlackWhiteValid/0');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (63, '002001008', '白名单', '', '', 'sys_coop_white', '', 23, '23,4', 8, 1, '2', 58, '2019-08-23 16:11:56', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', 3, '/coop/modifyBlackWhiteValid/1');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (64, '002001006', '客商解锁', '', '', 'sys_coop_unlock', '', 23, '23,4', 6, 1, '2', 58, '2019-08-23 16:12:19', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', 3, '/coop/unlock');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (65, '002001004', '移动客商资料', '', '', 'sys_coop_move', '', 23, '23,4', 4, 0, '2', 58, '2019-08-23 16:12:55', NULL, 'PRM', 'true', 'false', NULL, NULL, NULL, b'0', 3, '/coop/move');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (68, '001004007', '导出部门', '', '', 'sys_dept_export', '', 15, '15,1', 7, 0, '2', 58, '2019-08-23 16:15:12', NULL, 'HRS', 'true', 'true', NULL, NULL, NULL, b'0', 6, '/dept/exportExcel');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (76, '002006001', '生成账单', '', '', 'sys_coop_bill_add', '', 45, '45,4', 1, 1, '2', 58, '2019-08-23 16:18:18', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (77, '002006002', '数据填充', '', '', 'sys_coop_bill_fill', '', 45, '45,4', 2, 1, '2', 58, '2019-08-23 16:18:38', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (82, '001001004', '重置密码', '', '', 'sys_org_resetpass', '', 7, '7,1', 4, 1, '2', 58, '2019-08-23 16:29:28', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 3, '/org/resetPassward');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (83, '001001005', '配置权限', '', '', 'sys_org_permission', '', 7, '7,1', 5, 1, '2', 58, '2019-08-23 16:29:51', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 1, '/org/org-permission');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (85, '001006009', '兼职删除', '', '', 'sys_user_parttime_del', '', 2, '2,1', 9, 1, '2', 4, '2019-08-28 09:53:42', NULL, 'HRS', 'true', 'true', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (86, '002001005', '客商锁定', '', '', 'sys_coop_lock', '', 23, '23,4', 5, 1, '2', 4, '2019-08-28 10:01:58', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', 3, '/coop/lock');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (87, '002001009', '新建联系地址', '', '', 'sys_coop_address_save', '', 23, '23,4', 9, 1, '2', 4, '2019-08-28 10:30:09', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (88, '002001010', '修改联系地址', '', '', 'sys_coop_address_edit', '', 23, '23,4', 10, 1, '2', 4, '2019-08-28 10:31:28', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (89, '002001011', '新建业务范畴', '', '', 'sys_coop_scope_save', '', 23, '23,4', 11, 1, '2', 4, '2019-08-28 10:34:48', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (90, '002001012', '修改业务范畴', '', '', 'sys_coop_scope_edit', '', 23, '23,4', 12, 1, '2', 4, '2019-08-28 10:35:44', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (91, '002001013', '新建联系人', '', '', 'sys_coop_contact_save', '', 23, '23,4', 13, 1, '2', 4, '2019-08-28 10:37:28', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (92, '002001014', '修改联系人', '', '', 'sys_coop_contact_edit', '', 23, '23,4', 14, 1, '2', 4, '2019-08-28 10:38:27', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (96, '005004', '空运出口', '', '', '', 'el-icon-mychukou iconfont', 32, '32', 4, 0, '1', 3, '2019-09-20 14:08:34', NULL, 'TMS-AF', 'true', 'false', NULL, NULL, NULL, b'1', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (97, '005004001', 'AE订单', '/af_order', '/af_order', '', 'iconfont el-icon-mychukoufuwu', 96, '96,32', 1, 1, '1', 3, '2019-09-20 14:24:23', NULL, 'TMS-AF', 'false', 'false', NULL, 'AE订单-21.9.28.pdf', 'http://doc.efreight.cn/public/help/help_document_210928172426_AE订单-21.9.28.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (99, '005004002', '操作计划', '/af_operationPlan', '/af_operationPlan', '', 'iconfont el-icon-myplan', 96, '96,32', 2, 1, '1', 4, '2019-09-23 14:03:35', NULL, 'TMS-AF', 'false', 'false', NULL, '操作计划-21.4.27.pdf', 'http://doc.efreight.cn/public/help/help_document_210427174309_操作计划-21.4.27.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (103, '005004008', '单证制作', '/af_awbPrint', '/af_awbPrint', '', 'iconfont el-icon-mydanzhengguanli', 96, '96,32', 8, 0, '1', 4, '2019-10-11 16:19:04', NULL, 'TMS-AF', 'true', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (106, '003001007001', 'TACT-创建', '', '', 'sys_base_tact_add', '', 133, '133,41', 1, 1, '2', 1, '2019-10-29 15:34:27', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (107, '003001007002', 'TACT-修改', '', '', 'sys_base_tact_edit', '', 133, '133,41', 2, 1, '2', 1, '2019-10-29 15:35:52', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (108, '003001007003', 'TACT-删除', '', '', 'sys_base_tact_del', '', 133, '133,41', 3, 1, '2', 1, '2019-10-29 15:36:24', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (113, '002007002', '发送账单', '', '', 'sys_coop_bill_send', '', 101, '101,4', 2, 1, '2', 131, '2019-11-04 11:05:57', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (114, '002007003', '账单开票', '', '', 'sys_coop_bill_invoice', '', 101, '101,4', 3, 1, '2', 131, '2019-11-04 11:37:13', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (115, '002007004', '发票核销', '', '', 'sys_coop_bill_verify', '', 101, '101,4', 4, 1, '2', 131, '2019-11-04 11:38:47', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (116, '002007005', '查看账单', '', '', 'sys_coop_bill_checkbill', '', 101, '101,4', 5, 1, '2', 131, '2019-11-04 11:40:12', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (117, '002007006', '打印账单', '', '', 'sys_coop_bill_printbill', '', 101, '101,4', 6, 1, '2', 131, '2019-11-04 11:41:12', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (118, '002007007', '删除账单', '', '', 'sys_coop_bill_delete', '', 101, '101,4', 7, 1, '2', 131, '2019-11-04 11:42:09', NULL, 'PRM', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (119, '003001004001', '机场-创建', '', '', 'sys_base_airport_add', '', 130, '130,41', 4, 1, '2', 1, '2019-11-04 11:43:37', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (120, '003001004002', '机场-修改', '', '', 'sys_base_airport_edit', '', 130, '130,41', 4, 1, '2', 1, '2019-11-04 11:44:36', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (125, '002003007', '记录', '', '', 'sys_coop_agreement_list', '', 35, '35,4', 7, 1, '2', 131, '2019-11-04 14:49:20', NULL, 'PRM', 'true', 'false', NULL, NULL, NULL, b'0', 4, '/coopagreement/querySigningList');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (126, '004002099', '参数表', '', '', 'sys_base_category', '', 41, '41,32', 99, 1, '2', 1, '2019-11-05 09:45:01', NULL, 'TMS-AF', 'true', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (127, '004002001', '主单号管理', '/af_awb', '/af_awb', 'sys_base_awb', 'iconfont el-icon-myplan', 41, '41,32', 1, 1, '1', 1, '2019-11-05 09:46:07', NULL, 'TMS-AF', 'false', 'false', NULL, '主单号管理-21.3.22.pdf', 'http://doc.efreight.cn/public/help/help_document_210322133344_主单号管理-21.3.22.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (128, '003001002001', '主单号管理-新增', '', '', 'sys_base_awb_add', '', 127, '127,41', 2, 1, '2', 1, '2019-11-05 09:47:12', NULL, 'TMS-AF', 'false', 'false', NULL, '航空货物安全检查申报单.pdf', 'http://doc.efreight.cn/EFTBJS_helpDocumentUrl_航空货物安全检查申报单.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (130, '004002003', '机场信息', '/af_airport', '/af_airport', 'sys_base_airport', 'el-icon-mychukou iconfont', 41, '41,268', 3, 1, '1', 1, '2019-11-05 09:48:05', NULL, 'TMS-AF', 'false', 'false', NULL, '机场查询.pdf', 'http://doc.efreight.cn/public/help/help_document_210322133615_机场查询.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (131, '004002004', '货站仓库', '/af_warehouse', '/af_warehouse', 'sys_base_warehouse', 'el-icon-s-finance', 41, '41,32', 4, 1, '1', 1, '2019-11-05 09:48:39', NULL, 'TMS-AF', 'false', 'false', NULL, '库房设置.pdf', 'http://doc.efreight.cn/public/help/help_document_210622173720_货站仓库-21.6.22.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (132, '004002006', '航空公司', '/af_carrier', '/af_carrier', 'sys_base_carrier', 'el-icon-myjinkou iconfont', 41, '41,32', 6, 1, '1', 1, '2019-11-05 09:49:08', NULL, 'TMS-AF', 'false', 'false', NULL, '航空公司.pdf', 'http://doc.efreight.cn/public/help/help_document_210322135356_航空公司.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (133, '004002009', 'TACT', '/af_tact', '/af_tact', 'sys_base_tact', 'el-icon-myzhanglingfenxi iconfont', 41, '41,32', 9, 1, '1', 1, '2019-11-05 09:49:28', NULL, 'TMS-AF', 'false', 'false', NULL, 'TACT-2020.12.30 (2).pdf', 'http://doc.efreight.cn/public/help/help_document_210322135610_TACT-2020.12.30 (2).pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (134, '004002007', '航班信息', '/af_flight', '/af_flight', 'sys_base_flight', 'el-icon-myjinkou iconfont', 41, '41,32', 7, 1, '1', 1, '2019-11-05 09:49:47', NULL, 'TMS-AF', 'false', 'false', NULL, '航班信息-2020.12.30.pdf', 'http://doc.efreight.cn/public/help/help_document_210322135425_航班信息-2020.12.30.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (136, '004002010', '操作日志', '', '', 'sys_base_log', '', 41, '41,32', 10, 1, '2', 1, '2019-11-05 09:50:30', NULL, 'TMS-AF', 'true', 'true', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (137, '003001002002', '主单号管理-删除', '', '', 'sys_base_awb_del', '', 127, '127,41', 2, 1, '2', 1, '2019-11-05 09:59:47', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (138, '003001005001', '货站/仓库-新建', '', '', 'sys_base_warehouse_add', '', 131, '131,41', 5, 1, '2', 1, '2019-11-05 10:02:47', NULL, 'TMS-AF', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (139, '003001005002', '货站/仓库-修改', '', '', 'sys_base_warehouse_edit', '', 131, '131,41', 5, 1, '2', 1, '2019-11-05 10:03:17', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (140, '003001006001', '航司-新增', '', '', 'sys_base_carrier_add', '', 132, '132,41', 6, 1, '2', 1, '2019-11-05 10:06:20', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (141, '003001006002', '航司-编辑', '', '', 'sys_base_carrier_edit', '', 132, '132,41', 6, 1, '2', 1, '2019-11-05 10:06:45', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (142, '003001006003', '航司-删除', '', '', 'sys_base_carrier_del', '', 132, '132,41', 6, 1, '2', 1, '2019-11-05 10:07:08', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (144, '003001008001', '航班-新增', '', '', 'sys_base_flight_add', '', 134, '134,41', 8, 1, '2', 1, '2019-11-05 10:15:41', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (145, '003001008002', '航班-编辑', '', '', 'sys_base_flight_edit', '', 134, '134,41', 8, 1, '2', 1, '2019-11-05 10:16:47', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (146, '003001008003', '航班-删除', '', '', 'sys_base_flight_del', '', 134, '134,41', 8, 1, '2', 1, '2019-11-05 10:17:50', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (148, '001006007', '兼职', '', '', 'sys_user_parttime', '', 2, '2,1', 7, 1, '2', 200, '2019-11-05 10:19:47', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (149, '001007001', '新增公告', '', '', 'sys_notice_add', '', 42, '42,1', 1, 1, '2', 200, '2019-11-05 10:31:23', NULL, 'HRS', 'false', 'true', NULL, NULL, NULL, b'0', 1, '/notice');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (150, '001008001', '新增版本', '', '', 'sys_version_add', '', 43, '43,1', 1, 1, '2', 200, '2019-11-05 10:37:33', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 1, '/version');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (152, '001008002', '编辑版本', '', '', 'sys_version_edit', '', 43, '43,1', 2, 1, '2', 200, '2019-11-05 10:38:36', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 3, '/version');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (153, '001008003', '记录版本', '', '', 'sys_version_record', '', 43, '43,1', 3, 1, '2', 200, '2019-11-05 10:39:22', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 3, '/version/child');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (154, '001008004', '删除版本', '', '', 'sys_version_del', '', 43, '43,1', 4, 1, '2', 200, '2019-11-05 10:40:06', NULL, 'HRS', 'true', 'false', NULL, NULL, NULL, b'0', 2, '/version/child/{recordId}');
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (155, '007', '财务结算管理', '', '', '', 'el-icon-myjiesuanguanli iconfont', -1, '-1', 8, 1, '0', 4, '2019-11-06 17:38:35', NULL, 'CSS', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (156, '006003', '收入对账', '/css_debit_note', '/css_debit_note', '', 'el-icon-myyingshouzhangdan iconfont', 155, '155,32', 3, 1, '1', 4, '2019-11-06 17:39:30', NULL, 'TMS-AF', 'false', 'false', NULL, '收入对账-21.8.6.pdf', 'http://doc.efreight.cn/public/help/help_document_210806172943_收入对账-21.8.6.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (159, '001', '新增订单', '', '', 'af-order-add', '', 97, '97,96', 1, 1, '2', 3, '2019-11-12 18:07:54', NULL, 'TMS-AF', 'false', 'false', NULL, 'AE订单-21.9.28.pdf', 'http://doc.efreight.cn/public/help/help_document_210928172601_AE订单-21.9.28.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (160, '002', '编辑订单', '', '', 'af-order-edit', '', 97, '97,96', 3, 1, '2', 3, '2019-11-13 09:52:17', NULL, 'TMS-AF', 'false', 'false', NULL, 'AE编辑订单-21.3.29.pdf', 'http://doc.efreight.cn/public/help/help_document_210329170125_AE编辑订单-21.3.29.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (161, '023009', '卸载主单', '', '', 'af-order-uninstall', '', 249, '249', 9, 1, '2', 3, '2019-11-13 09:55:14', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (163, '005', '舱单信息', '', '', 'af-order-letter', '', 97, '97,96', 4, 1, '2', 3, '2019-11-13 10:01:36', NULL, 'TMS-AF', 'true', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (164, '006', '费用录入', '', '', 'af-order-services', '', 97, '97,96', 6, 1, '2', 3, '2019-11-13 10:07:36', NULL, 'TMS-AF', 'false', 'false', NULL, 'AE费用录入-21.8.4.pdf', 'http://doc.efreight.cn/public/help/help_document_210804180337_AE费用录入-21.8.4.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (165, '023014', '强制关闭', '', '', 'af-order-forcestop', '', 249, '249', 14, 1, '2', 3, '2019-11-13 10:10:26', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (166, '008', '单货匹配', '', '', 'af-order-match', '', 97, '97,96', 7, 1, '2', 3, '2019-11-13 10:11:29', NULL, 'TMS-AF', 'true', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (167, '022008', '订舱托书', '', '', 'af-order-printletter', '', 248, '248', 8, 1, '2', 3, '2019-11-13 10:13:34', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (168, '022009', '运单确认件', '', '', 'af-order-awbsubmit', '', 248, '248', 9, 1, '2', 3, '2019-11-13 10:14:41', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (169, '011', '出重信息', '', '', 'af-order-weighttag', '', 97, '97,96', 5, 1, '2', 3, '2019-11-13 10:19:11', NULL, 'TMS-AF', 'false', 'false', NULL, '3.操作出重-2021.8.5.pdf', 'http://doc.efreight.cn/public/help/help_document_210805180058_3.操作出重-2021.8.5.pdf', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (170, '012', '日志查看', '', '', 'af-order-logtag', '', 97, '97,96', 12, 1, '2', 3, '2019-11-13 10:19:58', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (171, '001', '查看订单', '', '', 'af-order-view', '', 97, '97,96', 2, 1, '2', 3, '2019-11-13 10:44:11', NULL, 'TMS-AF', 'false', 'false', NULL, NULL, NULL, b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (172, '002009001', '新增', '', '', 'sys_coop_service_add', '', 158, '158,4', 1, 1, '2', 1, '2019-11-18 17:28:32', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (174, '002009003', '编辑', '', '', 'sys_coop_service_edit', '', 158, '158,4', 3, 1, '2', 1, '2019-11-18 17:30:31', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (175, '002003001', '新增账单客户', '', '', 'sys_coop_settlement_addbillcustomer', '', 36, '36,4', 1, 1, '2', 1, '2019-11-18 17:44:52', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (176, '002003002', '新增账单模板', '', '', 'sys_coop_settlement_addbilltemplate', '', 36, '36,4', 2, 1, '2', 1, '2019-11-18 17:45:59', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (177, '002003003', '编辑', '', '', 'sys_coop_settlement_edit', '', 36, '36,4', 3, 1, '2', 1, '2019-11-18 17:46:38', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (178, '002003004', '删除', '', '', 'sys_coop_settlement_del', '', 36, '36,4', 4, 1, '2', 1, '2019-11-18 17:47:21', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (179, '002003005', '生效', '', '', 'sys_coop_settlement_valid', '', 36, '36,4', 5, 1, '2', 1, '2019-11-18 17:48:03', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (180, '002003006', '失效', '', '', 'sys_coop_settlement_invalid', '', 36, '36,4', 6, 1, '2', 1, '2019-11-18 17:48:44', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (181, '002007008', '销售确认', '', '', 'sys_coop_bill_saleconfirm', '', 101, '101,4', 8, 1, '2', 1, '2019-11-18 18:09:29', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (182, '002007009', '总部确认', '', '', 'sys_coop_bill_baseconfirm', '', 101, '101,4', 9, 1, '2', 1, '2019-11-18 18:10:52', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (183, '002007010', '客户确认', '', '', 'sys_coop_bill_customerconfirm', '', 101, '101,4', 10, 1, '2', 1, '2019-11-18 18:11:42', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (184, '021017001', '制作主单', '', '', 'af_button_awbPrint_saveMawb', '', 243, '243', 1, 1, '2', 4, '2019-11-20 15:30:30', NULL, 'TMS-AF', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (185, '021017002', '制作分单', '', '', 'af_button_awbPrint_saveHawb', '', 243, '243', 2, 1, '2', 4, '2019-11-20 15:31:34', NULL, 'TMS-AF', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (186, '021017003', '主单编辑', '', '', 'af_button_awbPrint_editMawb', '', 243, '243', 3, 1, '2', 4, '2019-11-20 15:32:21', NULL, 'TMS-AF', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (187, '021017004', '分单编辑', '', '', 'af_button_awbPrint_editHawb', '', 243, '243', 4, 1, '2', 4, '2019-11-20 15:33:23', NULL, 'TMS-AF', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (188, '021017005', '发送主单', '', '', 'af_button_awbPrint_sendMawb', '', 243, '243', 5, 1, '2', 4, '2019-11-20 15:34:35', NULL, 'TMS-AF', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (189, '021017006', '发送分单', '', '', 'af_button_awbPrint_sendHawb', '', 243, '243', 6, 1, '2', 4, '2019-11-20 15:35:29', NULL, 'TMS-AF', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (190, '021017007', '主单完成', '', '', 'af_button_awbPrint_finishMawb', '', 243, '243', 7, 1, '2', 4, '2019-11-20 15:36:20', NULL, 'TMS-AF', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (191, '021017008', '分单完成', '', '', 'af_button_awbPrint_finishHawb', '', 243, '243', 8, 1, '2', 4, '2019-11-20 15:36:48', NULL, 'TMS-AF', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (195, '003001004', '收费项目', '/prm_service', '/prm_service', '', 'el-icon-s-order', 601, '601,4', 4, 1, '1', 1, '2019-11-20 18:57:10', NULL, 'PRM', 'false', 'false', '', '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (196, '002010001001', '新增', '', '', 'sys_coop_service_add', '', 195, '195,194', 1, 1, '2', 1, '2019-11-20 18:59:21', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (197, '002010001002', '新增服务', '', '', 'sys_coop_service_addservice', '', 195, '195,194', 2, 1, '2', 1, '2019-11-20 19:00:23', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (198, '002010001003', '编辑', '', '', 'sys_coop_service_edit', '', 195, '195,194', 3, 1, '2', 1, '2019-11-20 19:01:29', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (199, '003002001', '账单模板', '/prm_coop_agreement_settlement', '/prm_coop_agreement_settlement', '', 'el-icon-s-finance', 602, '602,4', 1, 1, '1', 1, '2019-11-20 19:03:01', NULL, 'PRM', 'false', 'false', '', '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (200, '002010002001', '新增账单客户', '', '', 'sys_coop_settlement_addbillcustomer', '', 199, '199,194', 1, 1, '2', 1, '2019-11-20 19:04:01', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (201, '002010002002', '新增账单模板', '', '', 'sys_coop_settlement_addbilltemplate', '', 199, '199,194', 2, 1, '2', 1, '2019-11-20 19:04:58', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (202, '002010002003', '编辑', '', '', 'sys_coop_settlement_edit', '', 199, '199,194', 3, 1, '2', 1, '2019-11-20 19:05:46', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (203, '002010002004', '删除', '', '', 'sys_coop_settlement_del', '', 199, '199,194', 4, 1, '2', 1, '2019-11-20 19:06:29', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (204, '002010002005', '财务审核', '', '', 'sys_coop_settlement_valid', '', 199, '199,194', 5, 1, '2', 1, '2019-11-20 19:07:14', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (205, '002010002006', '失效', '', '', 'sys_coop_settlement_invalid', '', 199, '199,194', 6, 1, '2', 1, '2019-11-20 19:08:03', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (206, '003002002', '账单生成', '/prm_coop_bill', '/prm_coop_bill', '', 'el-icon-s-order', 602, '602,4', 2, 1, '1', 1, '2019-11-20 19:09:20', NULL, 'PRM', 'false', 'false', '', '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (207, '002010003001', '生成账单', '', '', 'sys_coop_bill_add', '', 206, '206,194', 1, 1, '2', 1, '2019-11-20 19:10:04', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (208, '002010003002', '数据填充', '', '', 'sys_coop_bill_fill', '', 206, '206,194', 2, 1, '2', 1, '2019-11-20 19:10:47', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (209, '003002003', '账单确认', '/prm_coop_check', '/prm_coop_check', '', 'el-icon-s-order', 602, '602,4', 3, 1, '1', 1, '2019-11-20 19:11:54', NULL, 'PRM', 'false', 'false', '', '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (210, '002010004011003', '发送账单', '', '', 'sys_coop_bill_send', '', 637, '209,194', 3, 1, '2', 1, '2019-11-20 19:12:40', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (211, '002010004012007', '开具发票', '', '', 'sys_coop_bill_invoice', '', 638, '209,194', 7, 1, '2', 1, '2019-11-20 19:13:12', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (212, '002010004012008', '发票核销', '', '', 'sys_coop_bill_verify', '', 638, '209,194', 8, 1, '2', 1, '2019-11-20 19:13:47', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (213, '002010004012001', '查看账单', '', '', 'sys_coop_bill_checkbill', '', 638, '209,194', 1, 1, '2', 1, '2019-11-20 19:14:23', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (214, '002010004011002', '账单预览', '', '', 'sys_coop_bill_printbill', '', 637, '209,194', 2, 1, '2', 1, '2019-11-20 19:14:58', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (215, '002010004011009', '删除账单', '', '', 'sys_coop_bill_delete', '', 637, '209,194', 9, 1, '2', 1, '2019-11-20 19:15:33', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (216, '002010004011004', '销售确认', '', '', 'sys_coop_bill_saleconfirm', '', 637, '209,194', 4, 1, '2', 1, '2019-11-20 19:16:17', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
INSERT INTO `cargo`.`hrs_permission` (`permission_id`, `permission_code`, `permission_name`, `path`, `url`, `permission`, `icon`, `parent_id`, `parent_ids`, `sort`, `status`, `permission_type`, `creator_id`, `create_time`, `stop_date`, `app_code`, `disabled`, `admin_default`, `able_Orgid`, `help_document_name`, `help_document_url`, `customized`, `url_crud`, `mapping_url`) VALUES (217, '002010004011005', '总部确认', '', '', 'sys_coop_bill_baseconfirm', '', 637, '209,194', 5, 1, '2', 1, '2019-11-20 19:16:57', NULL, 'PRM', 'false', 'false', NULL, '', '', b'0', NULL, NULL);
